import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import GridPattern from "@/components/magicui/grid-pattern";
import { cn } from "@/lib/utils";


const mont  = Montserrat({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mont.className} antialiased`}>
        <Navbar/>
        {children}

        <GridPattern
          width={30}
          height={30}
          x={-1}
          y={-1}
          strokeDasharray={"4 2 "}
          className={cn(
            "[mask-image:radial-gradient(600px_circle_at_center,white,transparent)] opacity-50 -z-10",
          )}
        />
      </body>
    </html>
  );
}


